#<font color='red'>  Seq2Seq Model for Text Generation</font>

## 1. Import a. Keras model - Sequential, b. Keras layers - Dense and SimpleRNN.

In [2]:
from numpy import array
from pickle import dump 
from keras.utils import to_categorical
from keras.utils.vis_utils import plot_model
from keras.preprocessing.sequence import pad_sequences     
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import SimpleRNN, LSTM, GRU

# 2. Load the document in the memory.

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [3]:
# load doc into memory
def load_doc(filename):
    # open the file as read only
    file = open(filename, 'r')
    # read all text
    text = file.read()
    # close the file
    file.close()
    return text

# load text
### insert our code here -- call load_doc() function to load the contents of 'shakespeare.txt' into 'raw_text'
raw_text = load_doc('/content/drive/MyDrive/IITR_CV/Day_3_seq2seq/input.txt')

### insert our code here -- print 'raw_text'
print(raw_text)

From fairest creatures we desire increase,
That thereby beauty's rose might never die,
But as the riper should by time decease,
His tender heir might bear his memory:
But thou contracted to thine own bright eyes,
Feed'st thy light's flame with self-substantial fuel,
Making a famine where abundance lies,
Thy self thy foe, to thy sweet self too cruel:
Thou that art now the world's fresh ornament,
And only herald to the gaudy spring,
Within thine own bud buriest thy content,
And tender churl mak'st waste in niggarding:
Pity the world, or else this glutton be,
To eat the world's due, by the grave and thee.


# 3. Clean the tokens, print and observe them.

In [4]:
# clean
### insert our code here -- split the text and save tokens
tokens = raw_text.split()
print (tokens)

['From', 'fairest', 'creatures', 'we', 'desire', 'increase,', 'That', 'thereby', "beauty's", 'rose', 'might', 'never', 'die,', 'But', 'as', 'the', 'riper', 'should', 'by', 'time', 'decease,', 'His', 'tender', 'heir', 'might', 'bear', 'his', 'memory:', 'But', 'thou', 'contracted', 'to', 'thine', 'own', 'bright', 'eyes,', "Feed'st", 'thy', "light's", 'flame', 'with', 'self-substantial', 'fuel,', 'Making', 'a', 'famine', 'where', 'abundance', 'lies,', 'Thy', 'self', 'thy', 'foe,', 'to', 'thy', 'sweet', 'self', 'too', 'cruel:', 'Thou', 'that', 'art', 'now', 'the', "world's", 'fresh', 'ornament,', 'And', 'only', 'herald', 'to', 'the', 'gaudy', 'spring,', 'Within', 'thine', 'own', 'bud', 'buriest', 'thy', 'content,', 'And', 'tender', 'churl', "mak'st", 'waste', 'in', 'niggarding:', 'Pity', 'the', 'world,', 'or', 'else', 'this', 'glutton', 'be,', 'To', 'eat', 'the', "world's", 'due,', 'by', 'the', 'grave', 'and', 'thee.']


In [5]:
### insert our code here -- print 'raw_text' after cleaning
raw_text = ' '.join(tokens)
print(raw_text)

From fairest creatures we desire increase, That thereby beauty's rose might never die, But as the riper should by time decease, His tender heir might bear his memory: But thou contracted to thine own bright eyes, Feed'st thy light's flame with self-substantial fuel, Making a famine where abundance lies, Thy self thy foe, to thy sweet self too cruel: Thou that art now the world's fresh ornament, And only herald to the gaudy spring, Within thine own bud buriest thy content, And tender churl mak'st waste in niggarding: Pity the world, or else this glutton be, To eat the world's due, by the grave and thee.


# 4. Print and save the character sequences into a .txt file.

In [6]:
#organize into sequences of characters
length = 20
sequences = list()

for i in range(length, len(raw_text)):
    # select sequence of tokens
    seq = raw_text[i-length:i]
    # store
    sequences.append(seq)

print('Total Sequences: %d' % len(sequences)) 
#Total Sequences: 589

### insert our code here -- print sequences
print(sequences)   

# save tokens to file, one dialog per line
def save_doc(lines, filename):
    data = '\n'.join(lines)
    file = open(filename, 'w')
    file.write(data)
    file.close()    

# save sequences to file
out_filename = 'char_sequences.txt'  

### insert our code here -- save the contents of handle 'param1' into the file named 'param2' using save_doc(param1, param2) function
save_doc(sequences, out_filename)

###Open and check the file.

Total Sequences: 589
['From fairest creatur', 'rom fairest creature', 'om fairest creatures', 'm fairest creatures ', ' fairest creatures w', 'fairest creatures we', 'airest creatures we ', 'irest creatures we d', 'rest creatures we de', 'est creatures we des', 'st creatures we desi', 't creatures we desir', ' creatures we desire', 'creatures we desire ', 'reatures we desire i', 'eatures we desire in', 'atures we desire inc', 'tures we desire incr', 'ures we desire incre', 'res we desire increa', 'es we desire increas', 's we desire increase', ' we desire increase,', 'we desire increase, ', 'e desire increase, T', ' desire increase, Th', 'desire increase, Tha', 'esire increase, That', 'sire increase, That ', 'ire increase, That t', 're increase, That th', 'e increase, That the', ' increase, That ther', 'increase, That there', 'ncrease, That thereb', 'crease, That thereby', 'rease, That thereby ', 'ease, That thereby b', 'ase, That thereby be', 'se, That thereby bea', 'e, That thereby b

# 5. Load the contents of the .txt file. Sort and print the contents line-wise, character-wise and their mapping.

In [7]:
#load
in_filename = 'char_sequences.txt'
### insert your code here -- load the contents of the .txt file into 'raw_text' using load_doc(param1)
raw_text = load_doc(in_filename)

lines = raw_text.split('\n')
chars = sorted(list(set(raw_text)))
mapping = dict((c, i) for i, c in enumerate(chars))

### insert our code here -- print 'lines'
### insert our code here -- print 'chars'
### insert our code here --  print 'mapping'
print(lines)
print(chars)
print(mapping)

['From fairest creatur', 'rom fairest creature', 'om fairest creatures', 'm fairest creatures ', ' fairest creatures w', 'fairest creatures we', 'airest creatures we ', 'irest creatures we d', 'rest creatures we de', 'est creatures we des', 'st creatures we desi', 't creatures we desir', ' creatures we desire', 'creatures we desire ', 'reatures we desire i', 'eatures we desire in', 'atures we desire inc', 'tures we desire incr', 'ures we desire incre', 'res we desire increa', 'es we desire increas', 's we desire increase', ' we desire increase,', 'we desire increase, ', 'e desire increase, T', ' desire increase, Th', 'desire increase, Tha', 'esire increase, That', 'sire increase, That ', 'ire increase, That t', 're increase, That th', 'e increase, That the', ' increase, That ther', 'increase, That there', 'ncrease, That thereb', 'crease, That thereby', 'rease, That thereby ', 'ease, That thereby b', 'ase, That thereby be', 'se, That thereby bea', 'e, That thereby beau', ', That thereby

# 6. Print and observe the Encoded Sequence.

In [9]:
lines[0]

'From fairest creatur'

In [10]:
[mapping[char] for char in line[0]]  

[35]

In [8]:
sequences = list()
for line in lines:
    #integer encode line
    encoded_seq = [mapping[char] for char in line]
    #store
    sequences.append(encoded_seq)
    print(line,' : ',encoded_seq)

### insert our code here -- print(sequences) 
print(sequences) 

#vocabulary size
vocab_size = len(mapping)
print('Vocabulary Size: %d' % vocab_size)

From fairest creatur  :  [8, 29, 27, 25, 1, 19, 14, 22, 29, 18, 30, 31, 1, 16, 29, 18, 14, 31, 32, 29]
rom fairest creature  :  [29, 27, 25, 1, 19, 14, 22, 29, 18, 30, 31, 1, 16, 29, 18, 14, 31, 32, 29, 18]
om fairest creatures  :  [27, 25, 1, 19, 14, 22, 29, 18, 30, 31, 1, 16, 29, 18, 14, 31, 32, 29, 18, 30]
m fairest creatures   :  [25, 1, 19, 14, 22, 29, 18, 30, 31, 1, 16, 29, 18, 14, 31, 32, 29, 18, 30, 1]
 fairest creatures w  :  [1, 19, 14, 22, 29, 18, 30, 31, 1, 16, 29, 18, 14, 31, 32, 29, 18, 30, 1, 34]
fairest creatures we  :  [19, 14, 22, 29, 18, 30, 31, 1, 16, 29, 18, 14, 31, 32, 29, 18, 30, 1, 34, 18]
airest creatures we   :  [14, 22, 29, 18, 30, 31, 1, 16, 29, 18, 14, 31, 32, 29, 18, 30, 1, 34, 18, 1]
irest creatures we d  :  [22, 29, 18, 30, 31, 1, 16, 29, 18, 14, 31, 32, 29, 18, 30, 1, 34, 18, 1, 17]
rest creatures we de  :  [29, 18, 30, 31, 1, 16, 29, 18, 14, 31, 32, 29, 18, 30, 1, 34, 18, 1, 17, 18]
est creatures we des  :  [18, 30, 31, 1, 16, 29, 18, 14, 31, 32, 29, 1

# 7. Print and observe the shape of the X & y.

In [11]:
sequences = array(sequences)
print('Sequences:\n',sequences)
print('X:\n',sequences[:,:-1])
print('y:\n',sequences[:,-1])

Sequences:
 [[ 8 29 27 ... 31 32 29]
 [29 27 25 ... 32 29 18]
 [27 25  1 ... 29 18 30]
 ...
 [ 1 15 35 ...  1 31 21]
 [15 35  1 ... 31 21 18]
 [35  1 31 ... 21 18 18]]
X:
 [[ 8 29 27 ... 14 31 32]
 [29 27 25 ... 31 32 29]
 [27 25  1 ... 32 29 18]
 ...
 [ 1 15 35 ... 17  1 31]
 [15 35  1 ...  1 31 21]
 [35  1 31 ... 31 21 18]]
y:
 [29 18 30  1 34 18  1 17 18 30 22 29 18  1 22 26 16 29 18 14 30 18  3  1
 12 21 14 31  1 31 21 18 29 18 15 35  1 15 18 14 32 31 35  2 30  1 29 27
 30 18  1 25 22 20 21 31  1 26 18 33 18 29  1 17 22 18  3  1  7 32 31  1
 14 30  1 31 21 18  1 29 22 28 18 29  1 30 21 27 32 24 17  1 15 35  1 31
 22 25 18  1 17 18 16 18 14 30 18  3  1  9 22 30  1 31 18 26 17 18 29  1
 21 18 22 29  1 25 22 20 21 31  1 15 18 14 29  1 21 22 30  1 25 18 25 27
 29 35  5  1  7 32 31  1 31 21 27 32  1 16 27 26 31 29 14 16 31 18 17  1
 31 27  1 31 21 22 26 18  1 27 34 26  1 15 29 22 20 21 31  1 18 35 18 30
  3  1  8 18 18 17  2 30 31  1 31 21 35  1 24 22 20 21 31  2 30  1 19 24
 14 25 18  

In [13]:
sequences = array(sequences)
X, y = sequences[:,:-1], sequences[:,-1]

### insert our code here -- print, sequences, X and Y
#print('Sequences:\n',sequences)
#print('X:\n',X)
#print('y:\n',y)

seq_x = [to_categorical(x, num_classes=vocab_size) for x in X]
X = array(seq_x)
y = to_categorical(y, num_classes=vocab_size)

print('X:\n',X)
print('y:\n',y)

### insert our code here -- print shape of X
print('\nShape of X', X.shape)
print('\nShape of y', y.shape)

X:
 [[[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 ...

 [[0. 1. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 1.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 1.]
  [0. 1. 0. ... 0. 0. 0.]
  ...
  [0. 1. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]

 [[0. 0. 0. ... 0. 0. 1.]
  [0. 1. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  ...
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]
  [0. 0. 0. ... 0. 0. 0.]]]
y:
 [[

# 8. Call model define function. Observe the training process.

In [14]:
#Function to define and compile the model.
# define the model
def define_model(X):
    model = Sequential()
    model.add(SimpleRNN(units=75, input_shape=(X.shape[1], X.shape[2]), return_sequences=True))
    model.add(LSTM(units=75, input_shape=(X.shape[1], X.shape[2])))
    #model.add(GRU(units=75, input_shape=(X.shape[1], X.shape[2])))
    model.add(Dense(vocab_size, activation='softmax'))

    # compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    
    # summarize defined model
    model.summary()
    # plot_model(model, to_file='model.png', show_shapes=True)
    return model

In [15]:
# define model
#model = define_model(X)
model = Sequential()
model.add(SimpleRNN(units=75, input_shape=(X.shape[1], X.shape[2]), return_sequences=True))
model.add(SimpleRNN(units=75, input_shape=(X.shape[1], X.shape[2]), return_sequences=True))
model.add(SimpleRNN(units=75, input_shape=(X.shape[1], X.shape[2]), return_sequences=True))
model.add(LSTM(units=75, input_shape=(X.shape[1], X.shape[2])))
#model.add(GRU(units=75, input_shape=(X.shape[1], X.shape[2])))
model.add(Dense(vocab_size, activation='softmax'))

# compile model
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

# summarize defined model
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn (SimpleRNN)       (None, 19, 75)            8400      
_________________________________________________________________
simple_rnn_1 (SimpleRNN)     (None, 19, 75)            11325     
_________________________________________________________________
simple_rnn_2 (SimpleRNN)     (None, 19, 75)            11325     
_________________________________________________________________
lstm (LSTM)                  (None, 75)                45300     
_________________________________________________________________
dense (Dense)                (None, 36)                2736      
Total params: 79,086
Trainable params: 79,086
Non-trainable params: 0
_________________________________________________________________


In [16]:
# fit model
### insert your code here -- call fit() function on model with parameters (X, y, epochs=100, verbose=2)
model.fit(X, y, epochs=100, verbose=2)

Epoch 1/100
19/19 - 0s - loss: 3.2854 - accuracy: 0.1426
Epoch 2/100
19/19 - 0s - loss: 3.0165 - accuracy: 0.1647
Epoch 3/100
19/19 - 0s - loss: 2.9856 - accuracy: 0.1749
Epoch 4/100
19/19 - 0s - loss: 2.9721 - accuracy: 0.1749
Epoch 5/100
19/19 - 0s - loss: 2.9516 - accuracy: 0.1749
Epoch 6/100
19/19 - 0s - loss: 2.9412 - accuracy: 0.1885
Epoch 7/100
19/19 - 0s - loss: 2.8858 - accuracy: 0.1834
Epoch 8/100
19/19 - 0s - loss: 2.7974 - accuracy: 0.2190
Epoch 9/100
19/19 - 0s - loss: 2.6825 - accuracy: 0.2343
Epoch 10/100
19/19 - 0s - loss: 2.5273 - accuracy: 0.2818
Epoch 11/100
19/19 - 0s - loss: 2.4115 - accuracy: 0.3328
Epoch 12/100
19/19 - 0s - loss: 2.2241 - accuracy: 0.3939
Epoch 13/100
19/19 - 0s - loss: 2.0539 - accuracy: 0.4261
Epoch 14/100
19/19 - 0s - loss: 1.9029 - accuracy: 0.4720
Epoch 15/100
19/19 - 0s - loss: 1.7334 - accuracy: 0.5178
Epoch 16/100
19/19 - 0s - loss: 1.6122 - accuracy: 0.5722
Epoch 17/100
19/19 - 0s - loss: 1.4850 - accuracy: 0.6248
Epoch 18/100
19/19 - 0s

# 9. Save the model.

In [17]:
# save the model to file
### insert your code -- call model.save() function with parameter = 'model.h5'
model.save('model.h5')

# save the mapping
dump(mapping, open('mapping.pkl', 'wb'))

# 10. Load the saved model.

In [18]:
from pickle import load
from keras.models import load_model

# load the model
### insert your code here -- call load_model() function with parameter = 'model.h5'
load_model('model.h5')

# load the mapping
mapping = load(open('mapping.pkl', 'rb'))

# 11. Generate the character sequences.

In [19]:
# Function to generate and print the character sequences.
# generate a sequence of characters with a language model
def generate_seq(model, mapping, seq_length, seed_text, n_chars):
    in_text = seed_text
    len(in_text)
    # generate a fixed number of characters
    for _ in range(n_chars):
        # encode the characters as integers
        encoded = [mapping[char] for char in in_text]
        # truncate sequences to a fixed length
        encoded = pad_sequences([encoded], maxlen=seq_length, truncating='pre')
        # one hot encode
        encoded = to_categorical(encoded, num_classes=len(mapping))
        encoded.shape
        #encoded = encoded.reshape(1,encoded.shape[0], encoded.shape[1])
        # predict character
        yhat = model.predict_classes(encoded, verbose=0)
        # reverse map integer to character
        out_char = ''
        for char, index in mapping.items():
            if index == yhat:
                out_char = char
                break
            # append to input
        in_text += out_char
    return in_text

# 12. Test the model

In [20]:
print('\n*******************\n')
# test start of rhyme
print(generate_seq(model, mapping, 12, 'From fairest', 70))
# test mid-line
print(generate_seq(model, mapping, 12, 'Making a famine', 70))

### insert our code here -- test the phrases that are not in the original test-data e.g. 'hello world'
print(generate_seq(model, mapping, 12, 'Hello world', 70))


*******************

Instructions for updating:
Please use instead:* `np.argmax(model.predict(x), axis=-1)`,   if your model does multi-class classification   (e.g. if it uses a `softmax` last-layer activation).* `(model.predict(x) > 0.5).astype("int32")`,   if your model does binary classification   (e.g. if it uses a `sigmoid` last-layer activation).
From faireste  ceaere d s d see  he hhe ded ded he ges dese eee,, Bes  eetee ie  r
Making a famine  e cere , s e see  he doe des te tee we ee  oe seesw sen , ee ,ee ,hh
Hello worldu wn e ee te,,ew wees hees s ee w ee s eees ee s s eee,  e d ser sse  


-----------------