In [1]:
import tensorflow 

In [2]:
tensorflow.__version__

'2.3.0'

In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### Vocabulary size
voc_size=10000

###One Hot Representation

In [7]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[4604, 8073, 6099, 4599], [4604, 8073, 6099, 7566], [4604, 4247, 6099, 2960], [1665, 527, 6599, 2162, 7376], [1665, 527, 6599, 2162, 4498], [4965, 4604, 2908, 6099, 2686], [1496, 5150, 4418, 2162]]


#Word Embedding Represntation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 4604 8073 6099 4599]
 [   0    0    0    0 4604 8073 6099 7566]
 [   0    0    0    0 4604 4247 6099 2960]
 [   0    0    0 1665  527 6599 2162 7376]
 [   0    0    0 1665  527 6599 2162 4498]
 [   0    0    0 4965 4604 2908 6099 2686]
 [   0    0    0    0 1496 5150 4418 2162]]


In [11]:
dim=10

In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_1 (Embedding)      (None, 8, 10)             100000    
Total params: 100,000
Trainable params: 100,000
Non-trainable params: 0
_________________________________________________________________


In [15]:
print(model.predict(embedded_docs))

[[[-0.00569308 -0.00196759  0.04746994  0.00752538 -0.03209772
    0.01575121  0.04804745  0.02121719 -0.01906345  0.00845637]
  [-0.00569308 -0.00196759  0.04746994  0.00752538 -0.03209772
    0.01575121  0.04804745  0.02121719 -0.01906345  0.00845637]
  [-0.00569308 -0.00196759  0.04746994  0.00752538 -0.03209772
    0.01575121  0.04804745  0.02121719 -0.01906345  0.00845637]
  [-0.00569308 -0.00196759  0.04746994  0.00752538 -0.03209772
    0.01575121  0.04804745  0.02121719 -0.01906345  0.00845637]
  [-0.0095775   0.04737971 -0.0489695  -0.01488992 -0.03347982
    0.00616367 -0.02762285  0.01789028 -0.03286801  0.03221298]
  [ 0.003139   -0.00097878  0.03619853 -0.02227399 -0.00534697
   -0.01376599 -0.00829327  0.036057    0.02150379 -0.03423721]
  [ 0.03887323 -0.00747802 -0.0429763   0.03883148 -0.03885895
   -0.02469854  0.04596139 -0.04537367 -0.03610962  0.02099607]
  [ 0.01247773  0.02586355 -0.00442929  0.04814162  0.00546242
    0.01618487  0.03754207  0.03919382 -0.007366

---